### ISSUE TITLE
Cám ơn

### ISSUE THREAD

**Issue by shinsenter** [tuanducdesign/tuanducdesign#3]
Cám ơn bạn đã dẫn link đến thư viện của mình.

https://tuanducdesign.com/blog/huong-dan-su-dung-thu-vien-deferjs-cua-mai-nhut-tan

Hiện tại mình đã launch v2.0 với performance tốt hơn, bạn có thể giúp mình update bài viết được không?
https://github.com/shinsenter/defer.js/

**Comment by tuanducdesign** [comment]
Okey

**Comment by tuanducdesign** [comment]
Mình đã cập nhật bài viết rồi nhé!
